name: Pipeline CI/CD

on: [push]

env:
  VERSION: "0.0.2"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run Maven
      run:  cd complete && mvn -ntp versions:set -DnewVersion=$VERSION && mvn -ntp clean package

    - name: Create Staging dir  
      run: mkdir staging && cp complete/target/*.jar staging
    
    - name: Upload Artifact  
      uses: actions/upload-artifact@v1
      with:
        name: package-$VERSION
        path: staging
